CREATE TABLE IF NOT EXISTS promotions (
    id CHAR(26) PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    path TEXT NOT NULL,
    link TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP
);