DO $$
BEGIN
    IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'area_type') THEN
        CREATE TYPE area_type AS ENUM ('interior', 'exterior');
    END IF;
END $$;

CREATE TABLE IF NOT EXISTS areas (
    id CHAR(26) PRIMARY KEY,
    name VARCHAR(255) NOT NULL,
    type AREA_TYPE NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT CURRENT_TIMESTAMP NOT NULL,
    deleted_at TIMESTAMP WITH TIME ZONE
);