# https://taskfile.dev

version: '3'

dotenv: ['.env']

vars:
  GREETING: Hello, World!

tasks:
  default:
    cmds:
      - echo "{{.GREETING}}"
    silent: true
  migrate:
    cmds:
      - migrate -path db/migrations -database "postgres://${DIGIHUB_POSTGRES_USER}:${DIGIHUB_POSTGRES_PASSWORD}@${DIGIHUB_POSTGRES_HOST}:${DIGIHUB_POSTGRES_PORT}/${DIGIHUB_POSTGRES_DB}?sslmode=${DIGIHUB_POSTGRES_SSL_MODE}" {{.cmd}}
  create-migration:
    cmds:
      - migrate create -ext sql -dir db/migrations/ {{.name}} -tz UTC
  seed:
    cmds:
      - go run ./cmd/bin/main.go seed -total={{.total}} -table={{.table}}
  dev:
    cmds:
      - go run ./cmd/bin/main.go
  daemon:
    cmds:
      - pmgo
  ws:
    cmds:
      - go run ./cmd/bin/main.go ws --port=8080
  build:
    cmds:
      - go build -o ./digihub-app ./cmd/bin/main.go
  build-dev:
    cmds:
      - go build -o ./digihub-app ./cmd/bin/main.go
      - pid=$(immortalctl status | awk '/immortal/{print $1}') && kill $pid
      - mv ./digihub-app ../binaries/
      - immortalctl -c ../binaries/immortal.yaml
  lint-fix:
    cmds:
      - gofmt -w .
  lint-ci:
    cmds:
      - golangci-lint run
  nats:
    cmds:
      - nats-server --js
  commit:
    cmds:
      - task lint-fix
      - task lint-ci
      - git add .
      - git commit -m "{{.msg}}"
